### ISSUE TITLE
Can't run app

### ISSUE THREAD

**Issue by ezequias** [stribny/auth-quickstart#2]
I am getting the following message when I try to run the application:

$ node app.js
module.js:327
    throw err;
    ^

Error: Cannot find module 'bcrypt'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\ezequ\Box Sync\OneDrive\_oraculo\cabeça\BI&BD\src\node-post\auth-quickstart\app\setupPassport.js:3:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

I even try to install bcrypt using npm but I wasn't able to install it (it asked for Python and I installed it also).

I would be glad for any information.

Sincerely
Ezequias

**Comment by patbsh** [comment]
The issue is probably solved already but the module has changed its name basically. It's now called "bcrypt-nodejs". 
So to solve the issue you simply need to
"npm i bcrypt-nodejs --save" and require it as "bcrypt-nodejs".
